services:
  simulator:
    image: ghcr.io/lordofthesnow/nfl-playoff-rankings-mc-sim:latest
    container_name: nfl-playoff-rankings-mc-sim
    build: .
    ports:
      - "8080:8080"
    environment:
      - SEASON=${SEASON:-}
    volumes:
      - ./data:/data
    shm_size: "64m"
